org.gradle.jvmargs=-Xmx900m -XX:MaxMetaspaceSize=420m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=false
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=false
kotlin.code.style=official
